server:
  port: 10004

spring:
  application:
    name: project-service
    index: 0

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/