server:
  port: 10009

spring:
  application:
    name: relation-service
    index: 0

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/