server:
  port: 10000

spring:
  application:
    name: user-service
    index: 7
  devtools:
    restart:
      additionalPaths: src/main/java/org.latheild.user

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/