server:
  port: 10001

spring:
  application:
    name: user-info-service
    index: 0
  devtools:
    restart:
      additionalPaths: src/main/java/org.latheild.userinfo

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/